### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Nord1cWarr1or** [yapb/yapb#354]
Сервер неожиданно упал. Лог указывает на Yapb.

Crash log:
```
----------------------------------------------
CRASH: Wed Jun 15 15:04:08 MSK 2022
Start Line: ./hlds_linux -game cstrike -strictportbind +ip  -port 27015 +clientport 27005 +map DustII2x2 +servercfgfile server.cfg -maxplayers 32 -pingboost 3 -debug -pidfile hlds.15460.pid
[New LWP 15472]
[New LWP 15512]
[New LWP 15504]
[New LWP 15505]
[New LWP 15507]
[New LWP 15511]
[New LWP 15513]
[New LWP 15514]
[New LWP 15515]
[New LWP 28434]
[New LWP 28435]
[New LWP 28436]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./hlds_linux -game cstrike -strictportbind +ip  -port 27015 +clientp'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0xf188dfd8 in BotGraph::getNearestNoBuckets(cr::Vec3D<float> const&, float, int) [clone .constprop.0] () from /home/public/serverfiles/cstrike/addons/yapb/bin/yapb.so
[Current thread is 1 (Thread 0xf73e5700 (LWP 15472))]
#0  0xf188dfd8 in BotGraph::getNearestNoBuckets(cr::Vec3D<float> const&, float, int) [clone .constprop.0] () from /home/public/serverfiles/cstrike/addons/yapb/bin/yapb.so
#1  0xf18a271e in BotGraph::erase(int) [clone .part.0] () from /home/public/serverfiles/cstrike/addons/yapb/bin/yapb.so
#2  0xf1905c84 in BotControl::menuGraphPage1(int) () from /home/public/serverfiles/cstrike/addons/yapb/bin/yapb.so
#3  0xf1938f13 in GetEntityAPI::{lambda(edict_s*)#7}::_FUN(edict_s*) () from /home/public/serverfiles/cstrike/addons/yapb/bin/yapb.so
#4  0xf0d7120c in ?? ()
#5  0x00000010 in ?? ()
#6  0xf6d44db1 in SV_ParseStringCommand(client_s*) () from /home/public/serverfiles/engine_i486.so
#7  0x00000001 in ?? ()
#8  0x00000003 in ?? ()
#9  0x000000df in ?? ()
#10 0x0b1d46c0 in ?? ()
#11 0xf6d48667 in IVoidHookChainImpl<IGameClient*, unsigned char>::callNext(IGameClient*, unsigned char) () from /home/public/serverfiles/engine_i486.so
#12 0xf6d4864e in IVoidHookChainImpl<IGameClient*, unsigned char>::callNext(IGameClient*, unsigned char) () from /home/public/serverfiles/engine_i486.so
#13 0xf6d4864e in IVoidHookChainImpl<IGameClient*, unsigned char>::callNext(IGameClient*, unsigned char) () from /home/public/serverfiles/engine_i486.so
#14 0xf6d11e0d in SV_ReadPackets() () from /home/public/serverfiles/engine_i486.so
#15 0x00000003 in ?? ()
#16 0x00000000 in ?? ()
No symbol table info available.
From        To          Syms Read   Shared Object Library
0xf76dca30  0xf76dd921  Yes (*)     /lib/i386-linux-gnu/libdl.so.2
0xf764f914  0xf7695c78  Yes         ./libstdc++.so.6
0xf75b86e0  0xf75effcb  Yes (*)     /lib/i386-linux-gnu/libm.so.6
0xf7413800  0xf754101f  Yes (*)     /lib/i386-linux-gnu/libc.so.6
0xf76f0860  0xf7709f1d  Yes (*)     /lib/ld-linux.so.2
0xf73e8e04  0xf73f8490  Yes         ./libgcc_s.so.1
0xf6d091d0  0xf6df8e90  Yes (*)     /home/public/serverfiles/engine_i486.so
0xf6ccd840  0xf6cd0dfc  Yes (*)     /lib/i386-linux-gnu/librt.so.1
0xf6cbb5c0  0xf6cc5d74  Yes (*)     ./libsteam_api.so
0xf6ca08c0  0xf6cadf01  Yes (*)     /lib/i386-linux-gnu/libpthread.so.0
0xf6c76e00  0xf6c92838  Yes (*)     /home/public/serverfiles/filesystem_stdio.so
0xf4f9d000  0xf647e1b4  Yes (*)     /home/public/.steam/sdk32/steamclient.so
0xf26376a0  0xf2679f70  Yes (*)     /home/public/serverfiles/./cstrike/addons/metamod/metamod_i386.so
0xf23d2500  0xf25696b0  Yes (*)     /home/public/serverfiles/cstrike/dlls/cs.so
0xf2268690  0xf227d014  Yes (*)     /home/public/serverfiles/cstrike/addons/SafeNameAndChat/SafeNameAndChat.so
0xf223f5d0  0xf2255d20  Yes (*)     /home/public/serverfiles/cstrike/addons/reunion/reunion_mm_i386.so
0xf2215b40  0xf221f0b0  Yes (*)     /home/public/serverfiles/cstrike/addons/reauthcheck/reauthcheck_mm_i386.so
0xf203ea20  0xf20a1db7  Yes (*)     /home/public/serverfiles/cstrike/addons/amxmodx/dlls/amxmodx_mm_i386.so
0xf1faae30  0xf20036e8  Yes (*)     cstrike/addons/amxmodx/modules/adminskit_amxx_i386.so
0xf1f7d130  0xf1f83810  Yes (*)     cstrike/addons/amxmodx/modules/reaimdetector_amxx_i386.so
0xf1f46aa0  0xf1f6a2f2  Yes (*)     /home/public/serverfiles/cstrike/addons/printcenterfix/printcenterfix_mm_i386.so
0xf1f06200  0xf1f19120  Yes (*)     /home/public/serverfiles/cstrike/addons/rechecker/rechecker_mm_i386.so
0xf1ef5b90  0xf1eff2f0  Yes (*)     /home/public/serverfiles/cstrike/addons/resemiclip/resemiclip_mm_i386.so
0xf1edc980  0xf1ee8d30  Yes (*)     /home/public/serverfiles/cstrike/addons/resrdetector/resrdetector_mm_i386.so
0xf1cf7da0  0xf1e0e174  Yes (*)     /home/public/serverfiles/cstrike/addons/revoice_plus/revoice_plus_mm.so
0xf1c32010  0xf1c9bd59  Yes (*)     /home/public/serverfiles/cstrike/addons/unprecacher/unprecacher_i386.so
0xf1b80340  0xf1b9348e  Yes (*)     /home/public/serverfiles/cstrike/addons/whblocker/whblocker_mm_i386.so
0xf187c7c0  0xf195b085  Yes (*)     /home/public/serverfiles/cstrike/addons/yapb/bin/yapb.so
0xf0d9e3d0  0xf0dcdbc4  Yes (*)     /home/public/serverfiles/cstrike/addons/hitbox_fix/hitbox_fix_mm_i386.so
0xf1a9d9d0  0xf1ac9d6c  Yes (*)     cstrike/addons/amxmodx/modules/fakemeta_amxx_i386.so
0xf08ff790  0xf0997fc5  Yes (*)     cstrike/addons/amxmodx/modules/mysql_amxx_i386.so
0xf0786b60  0xf07ce624  Yes (*)     cstrike/addons/amxmodx/modules/hamsandwich_amxx_i386.so
0xf07648b0  0xf07651d8  Yes (*)     cstrike/addons/amxmodx/modules/csx_amxx_i386.so
0xf06f53b0  0xf073cda0  Yes (*)     cstrike/addons/amxmodx/modules/reapi_amxx_i386.so
0xf06bfa50  0xf06c58e4  Yes (*)     cstrike/addons/amxmodx/modules/geoip_amxx_i386.so
0xeff7a040  0xf02ae1dc  Yes (*)     cstrike/addons/amxmodx/modules/grip_amxx_i386.so
0xefbeb9b0  0xefbefa08  Yes (*)     cstrike/addons/amxmodx/modules/nvault_amxx_i386.so
0xefbd9290  0xefbe580c  Yes (*)     cstrike/addons/amxmodx/modules/engine_amxx_i386.so
0xefb44d50  0xefb54460  Yes (*)     cstrike/addons/amxmodx/modules/cstrike_amxx_i386.so
0xefb30660  0xefb34f84  Yes (*)     cstrike/addons/amxmodx/modules/fun_amxx_i386.so
0xee003a80  0xee0098f0  Yes (*)     /lib/i386-linux-gnu/libnss_files.so.2
0xebbb9000  0xed04d1b4  Yes (*)     ./steamclient.so
0xedc6f670  0xedce5020  Yes (*)     ./crashhandler.so
0xedc58b50  0xedc5b7d6  Yes (*)     /lib/i386-linux-gnu/libnss_dns.so.2
0xedc42690  0xedc4eba4  Yes (*)     /lib/i386-linux-gnu/libresolv.so.2
0xeabdb9f0  0xeaca6434  Yes (*)     /usr/lib/i386-linux-gnu/libSDL2-2.0.so.0
0xeaac51b0  0xeab63f34  Yes (*)     /usr/lib/i386-linux-gnu/libasound.so.2
0xedc3af00  0xedc3c3e4  Yes (*)     /usr/lib/i386-linux-gnu/libpulse-simple.so.0
0xeb55fc90  0xeb58de74  Yes (*)     /usr/lib/i386-linux-gnu/libpulse.so.0
0xedc2a040  0xedc314d4  Yes (*)     /usr/lib/i386-linux-gnu/libsndio.so.6.1
0xea96d3a0  0xea9f7874  Yes (*)     /usr/lib/i386-linux-gnu/libX11.so.6
0xeb544870  0xeb54f1a4  Yes (*)     /usr/lib/i386-linux-gnu/libXext.so.6
0xedc1df40  0xedc230c4  Yes (*)     /usr/lib/i386-linux-gnu/libXcursor.so.1
0xeb53e850  0xeb53f274  Yes (*)     /usr/lib/i386-linux-gnu/libXinerama.so.1
0xeb52c980  0xeb5377a4  Yes (*)     /usr/lib/i386-linux-gnu/libXi.so.6
0xeb51f5e0  0xeb525cd4  Yes (*)     /usr/lib/i386-linux-gnu/libXrandr.so.2
0xeb51b9d0  0xeb51c788  Yes (*)     /usr/lib/i386-linux-gnu/libXss.so.1
0xeb514bd0  0xeb517584  Yes (*)     /usr/lib/i386-linux-gnu/libXxf86vm.so.1
0xeb5114e0  0xeb511751  Yes (*)     /usr/lib/i386-linux-gnu/libwayland-egl.so.1
0xeb505eb0  0xeb50a714  Yes (*)     /usr/lib/i386-linux-gnu/libwayland-client.so.0
0xeb4faca0  0xeb4fca74  Yes (*)     /usr/lib/i386-linux-gnu/libwayland-cursor.so.0
0xeb1a2a60  0xeb1be494  Yes (*)     /usr/lib/i386-linux-gnu/libxkbcommon.so.0
0xeb1203b0  0xeb1668f4  Yes (*)     /usr/lib/i386-linux-gnu/pulseaudio/libpulsecommon-10.0.so
0xeb4f4f10  0xeb4f6aa4  Yes (*)     /lib/i386-linux-gnu/libcap.so.2
0xea906cd0  0xea935354  Yes (*)     /lib/i386-linux-gnu/libdbus-1.so.3
0xea8e34b0  0xea8f6064  Yes (*)     /lib/i386-linux-gnu/libbsd.so.0
0xea8beb50  0xea8d36c4  Yes (*)     /usr/lib/i386-linux-gnu/libxcb.so.1
0xeb4e9430  0xeb4ef7f4  Yes (*)     /usr/lib/i386-linux-gnu/libXrender.so.1
0xeb10afe0  0xeb10d534  Yes (*)     /usr/lib/i386-linux-gnu/libXfixes.so.3
0xeb1020d0  0xeb106454  Yes (*)     /usr/lib/i386-linux-gnu/libffi.so.6
0xea8b23f0  0xea8b2542  Yes (*)     /usr/lib/i386-linux-gnu/libX11-xcb.so.1
0xea898630  0xea8a5ce4  Yes (*)     /usr/lib/i386-linux-gnu/libICE.so.6
0xea88c480  0xea890684  Yes (*)     /usr/lib/i386-linux-gnu/libSM.so.6
0xea883f20  0xea8869e4  Yes (*)     /usr/lib/i386-linux-gnu/libXtst.so.6
0xea677350  0xea6d4974  Yes (*)     /lib/i386-linux-gnu/libsystemd.so.0
0xea879c50  0xea87d9d4  Yes (*)     /lib/i386-linux-gnu/libwrap.so.0
0xea5e38d0  0xea63f564  Yes (*)     /usr/lib/i386-linux-gnu/libsndfile.so.1
0xea871d40  0xea8744d4  Yes (*)     /usr/lib/i386-linux-gnu/libasyncns.so.0
0xea86dbb0  0xea86e9d4  Yes (*)     /usr/lib/i386-linux-gnu/libXau.so.6
0xea866ea0  0xea868914  Yes (*)     /usr/lib/i386-linux-gnu/libXdmcp.so.6
0xea860fb0  0xea862b64  Yes (*)     /lib/i386-linux-gnu/libuuid.so.1
0xea838150  0xea850644  Yes (*)     /lib/i386-linux-gnu/libselinux.so.1
0xea809380  0xea822bf4  Yes (*)     /lib/i386-linux-gnu/liblzma.so.5
0xea5cda80  0xea5da904  Yes (*)     /usr/lib/i386-linux-gnu/liblz4.so.1
0xea502770  0xea579ea4  Yes (*)     /lib/i386-linux-gnu/libgcrypt.so.20
0xea4e6110  0xea4f1cf1  Yes (*)     /lib/i386-linux-gnu/libnsl.so.1
0xea48a7d0  0xea4d15e4  Yes (*)     /usr/lib/i386-linux-gnu/libFLAC.so.8
0xea47c400  0xea47fbb4  Yes (*)     /usr/lib/i386-linux-gnu/libogg.so.0
0xea451520  0xea466134  Yes (*)     /usr/lib/i386-linux-gnu/libvorbis.so.0
0xea3c9c50  0xea3cc2f4  Yes (*)     /usr/lib/i386-linux-gnu/libvorbisenc.so.2
0xea34af00  0xea39ada4  Yes (*)     /lib/i386-linux-gnu/libpcre.so.3
0xea334e20  0xea33efa4  Yes (*)     /lib/i386-linux-gnu/libgpg-error.so.0
0xf0d4ef60  0xf0d5024c  Yes (*)     cstrike/addons/amxmodx/modules/sockets_amxx_i386.so
0xf0ce75d0  0xf0d30548  Yes (*)     cstrike/addons/amxmodx/modules/regex_amxx_i386.so
(*): Shared library is missing debugging information.
Stack level 0, frame at 0xff99d3e0:
 eip = 0xf188dfd8 in BotGraph::getNearestNoBuckets(cr::Vec3D<float> const&, float, int) [clone .constprop.0]; saved eip = 0xf18a271e
 called by frame at 0xff99d420
 Arglist at 0xff99d3d0, args: 
 Locals at 0xff99d3d0, Previous frame's sp is 0xff99d3e0
 Saved registers:
  ebx at 0xff99d3d0, esi at 0xff99d3d4, edi at 0xff99d3d8, eip at 0xff99d3dc
End of crash report
----------------------------------------------
```

OC: `Debian 9`

ReHLDS Version:
```
Protocol version 48
Exe version 1.1.2.7/Stdio (cstrike)
ReHLDS version: 3.11.0.776-dev
Build date: 19:37:50 Apr 20 2022 (2930)
Build from: https://github.com/dreamstalker/rehlds/commit/3dc9f8c
```

Meta version:
```
Metamod-r v1.3.0.128, API (5:13)
Metamod-r build: 17:47:54 Aug 24 2018
Metamod-r from: https://github.com/theAsmodai/metamod-r/commit/0cf2f70
```
Game version:
```
ReGameDLL version: 5.21.0.546-dev
Build date: 15:32:48 Dec 28 2021
Build from: https://github.com/s1lentq/ReGameDLL_CS/commit/09a6c61
```

Yapb version:
```
v4.2.671
```

Meta list:
```
Currently loaded plugins:
      description           stat pend  file                        vers             src  load  unload
 [ 1] SafeNameAndChat       RUN   -    SafeNameAndChat.so          v1.2 Beta 3      ini  ANY   ANY  
 [ 2] Reunion               RUN   -    reunion_mm_i386.so          v0.1.92d         ini  Start Never
 [ 3] ReAuthCheck           RUN   -    reauthcheck_mm_i386.so      v0.1.6           ini  Start Never
 [ 4] AMX Mod X             RUN   -    amxmodx_mm_i386.so          v1.9.0.5294      ini  Start ANY  
 [ 5] Print Center Fix      RUN   -    printcenterfix_mm_i386.so   v2.0.1           ini  ANY   ANY  
 [ 6] Rechecker             RUN   -    rechecker_mm_i386.so        v2.5             ini  Chlvl ANY  
 [ 7] ReSemiclip            RUN   -    resemiclip_mm_i386.so       v2.3.9           ini  Chlvl ANY  
 [ 8] ReSRDetector          RUN   -    resrdetector_mm_i386.so     v0.1.0           ini  Chlvl ANY  
 [ 9] Revoice               RUN   -    revoice_plus_mm.so          v2.0.5           ini  ANY   Never
 [10] Ultimate Unprecacher  RUN   -    unprecacher_i386.so         vBeta 2.5.3      ini  Chlvl Chlvl
 [11] WHBlocker             RUN   -    whblocker_mm_i386.so        v1.5.697         ini  Chlvl ANY  
 [12] YaPB                  RUN   -    yapb.so                     v4.2.671         ini  Chlvl ANY  
 [13] HitBox Fix            RUN   -    hitbox_fix_mm_i386.so       v1.0.10          ini  Start ANY  
 [14] Admins Kit            RUN   -    adminskit_amxx_i386.so      v2.1.0-33af8d6   pl4  ANY   Never
 [15] ReAimDetector         RUN   -    reaimdetector_amxx_i386.so  v0.2.2           pl4  ANY   Never
 [16] FakeMeta              RUN   -    fakemeta_amxx_i386.so       v1.9.0.5294      pl4  ANY   ANY  
 [17] MySQL                 RUN   -    mysql_amxx_i386.so          v1.9.0.5294      pl4  ANY   ANY  
 [18] Ham Sandwich          RUN   -    hamsandwich_amxx_i386.so    v1.9.0.5294      pl4  ANY   ANY  
 [19] ReAPI                 RUN   -    reapi_amxx_i386.so          v5.21.0.252-dev  pl4  ANY   Never
 [20] GeoIP                 RUN   -    geoip_amxx_i386.so          v1.9.0.5294      pl4  ANY   ANY  
 [21] gRIP                  RUN   -    grip_amxx_i386.so           v0.1.5 Beta      pl4  ANY   ANY  
 [22] Engine                RUN   -    engine_amxx_i386.so         v1.9.0.5294      pl4  ANY   ANY  
 [23] CStrike               RUN   -    cstrike_amxx_i386.so        v1.9.0.5294      pl4  ANY   ANY  
 [24] Fun                   RUN   -    fun_amxx_i386.so            v1.9.0.5294      pl4  ANY   ANY  
24 plugins, 24 running
```

Amxx list:
```
Currently loaded plugins:
       name                    version     author            file             status   
 [  1] DiveBanX                2020.1      RevCrew           DiveBanX.amxx    running  
 [  2] AfterBan                2021.0      RevCrew           AfterBan.amxx    running  
 [  3] CSStatsX SQL            0.7.4+2     serfreeman1337    csstatsx_sql.am  running  
 [  4] Admin Commands          1.9.0.5294  AMXX Dev Team     admincmd.amxx    running  
 [  5] Multi-Lingual System    1.9.0.5294  AMXX Dev Team     multilingual.am  running  
 [  6] Menus Front-End         1.9.0.5294  AMXX Dev Team     menufront.amxx   running  
 [  7] Maps Menu               1.9.0.5294  AMXX Dev Team     mapsmenu.amxx    running  
 [  8] Admin Votes             1.9.0.5294  AMXX Dev Team     adminvote.amxx   running  
 [  9] Pause Plugins           1.9.0.5294  AMXX Dev Team     pausecfg.amxx    running  
 [ 10] Commands Menu           1.9.0.5294  AMXX Dev Team     cmdmenu.amxx     running  
 [ 11] Players Menu            1.9.0.5294  AMXX Dev Team     plmenu.amxx      running  
 [ 12] Stats Configuration     1.9.0.5294  AMXX Dev Team     statscfg.amxx    running  
 [ 13] Accuracy Fix            3.0         Numb              accuracy_fix.am  running  
 [ 14] AES: StatsX             0.5+1       serfreeman1337    aes_statsx_cstr  running  
 [ 15] [ReAPI] Advanced Team   0.1.3       Vaqtincha / Nord  AdvancedTeamCho  running  
 [ 16] AFK Control ReNew       1.3         neygomon          afk_control.amx  running  
 [ 17] Anti-HPP                1.0.0       medusa            anti_hpp.amxx    running  
 [ 18] CS:GO Assault Scope     0.3.1       Nordic Warrior    assault_scope_n  running  
 [ 19] AWP Limiter             0.0.10      Nordic Warrior    awp_limiter.amx  debug    
 [ 20] [BG] Provider: GeoIP    0.2         mx?!              bg_provider_geo  running  
 [ 21] [BG] Provider: ip-api.  0.1         mx?!              bg_provider_ip-  running  
 [ 22] 49 44 49                20 4E 41    58 59 49          block_msg.amxx   running  
 [ 23] Block repeats           1.0.1       Nordic Warrior    block_repeats.a  running  
 [ 24] Block grande info       1.0         neygomon          BlockGrenadeInf  running  
 [ 25] Bot Features            0.9         Vaqtincha         BotFeatures.amx  running  
 [ 26] Bypass Guard            1.0.1       mx?!              bypass_guard.am  running  
 [ 27] Check Awp Map: API      1.0.0 (+dg  Nordic Warrior    check_awp_api.a  running  
 [ 28] Style C4 Timer          3.1         OciXCrom          crx_c4timer.amx  running  
 [ 29] OciXCrom's Rank System  3.9.2       OciXCrom          crx_ranksystem.  running  
 [ 30] [GRENADE] Pop Grenades  2.3         EFFx & HamletEag  csgo_pop_grenad  running  
 [ 31] [Reapi] Custom Models   1.6.1       neygomon          custom_models.a  running  
 [ 32] Custom Smoke            1.09        bionext           custom_smoke.am  running  
 [ 33] Custom MOTDs            1.0.2       ArKaNeMaN         CustomMotds.amx  running  
 [ 34] GameName Changer        1.0.0       Nordic Warrior    GameNameChanger  running  
 [ 35] [GRENADE] Molotov       1.0.2       medusa            grenade_molotov  running  
 [ 36] GSClient Auth           1.0         Dev-MS.ru         gsclient.amxx    running  
 [ 37] Injection Med-Kit       1.1.2       Emma Jule         injection.amxx   running  
 [ 38] Keys Weapon             1.0.9       AMXX Store & Nor  keysweapon.amxx  running  
 [ 39] Kick Spamers            1.0.3c      gyxoBka           KickSpamer.amxx  running  
 [ 40] Kills Counter           0.3         serfreeman1337    kills_counter.a  running  
 [ 41] Knife Duel with Telepo  1.2         neygomon          knife_duel.amxx  running  
 [ 42] New buy menu            0.8.3c      Nordic Warrior    NewBuyMenu.amxx  running  
 [ 43] Advanced Kill Assists   1.3c        Xelson            next21_kill_ass  running  
 [ 44] [ReAPI] No Team Flash   0.0.3       Vaqtincha         no_team_flash.a  running  
 [ 45] Ping Control            1.31        neygomon          Ping_Control.am  running  
 [ 46] Plant Bonus             1.1.1       Nordic Warrior    plant_bonus.amx  running  
 [ 47] Primary Collector       0.0.1b      Vaqtincha         primary_collect  running  
 [ 48] Print VIP Connection    0.0.6       Albertio          print_vip_conne  running  
 [ 49] ReAimDetector API       0.2.2       ReHLDS Team       reaimdetector.a  running  
 [ 50] [ReAPI] Refill Ammo on  0.0.2       steelzzz          refill_ammo_on_  running  
 [ 51] Reklama                 20.05.2020  mx?!              reklama.amxx     running  
 [ 52] ReParachute             1.4         PurposeLess       reparachute.amx  running  
 [ 53] RS                      1.0         DES               rs.amxx          running  
 [ 54] Say me and Say hp       1.4         neygomon          sayme_reapi.amx  running  
 [ 55] Silent Knife and Grena  0.0.1       Albertio          silent_knife_an  running  
 [ 56] Simple Damager          2.1.0       fl0wer            simple_damager.  running  
 [ 57] Team Balance Control    1.3.9       gyxoBka           TeamBalanceCont  running  
 [ 58] Technical Works         0.1.0       Jumper            technical_works  running  
 [ 59] CS:GO Inspect Weapon    5.1.5       hellmonja         weapon_inspect.  running  
 [ 60] WeaponHudChanger        1.1.2       Nordic Warrior    WeaponHudChange  running  
 [ 61] CS:GO P2000             3.5.0-WF    Sneaky.amxx, dia  csgo_p2000.amxx  debug    
 [ 62] CS:GO Tec-9             2.7.0-WF    Sneaky.amxx, dia  csgo_tec9.amxx   debug    
 [ 63] CS:GO PP-19 Bizon       2.15.0a-WF  Sneaky.amxx, dia  csgo_bizon.amxx  debug    
 [ 64] CS:GO CZ75              2.5.1-WF    Sneaky.amxx, dia  csgo_cz75.amxx   debug    
 [ 65] CS:GO MAG-7             1.6.0-WF    Sneaky.amxx, dia  csgo_mag7.amxx   debug    
 [ 66] CSGO: MP5-SD            1.1.0-WF    Sneaky.amxx, dia  csgo_mp5sd.amxx  debug    
 [ 67] CS:GO Negev             1.4.0-WF    Sneaky.amxx, dia  csgo_negev.amxx  debug    
 [ 68] CS:GO Sawed-Off Shotgu  1.7.0-WF    Sneaky.amxx, dia  csgo_sawedoff.a  debug    
 [ 69] CS:GO M4A4              1.5.1-WF    Sneaky.amxx, dia  csgo_m4a4.amxx   debug    
 [ 70] ChatAdditions: Core     v1.9.2      Sergey Shorokhov  ChatAdditions_C  debug    
 [ 71] ChatAdditions: CSBans   v1.9.2      Sergey Shorokhov  CA_Storage_CSBa  debug    
 [ 72] CA: Mute                v1.9.2      Sergey Shorokhov  CA_Mute.amxx     debug    
 [ 73] CA Addon: Death mute    v1.9.2      Sergey Shorokhov  CA_Addon_DeathM  debug    
 [ 74] CA: Gag                 v1.9.2      Sergey Shorokhov  CA_Gag.amxx      debug    
 [ 75] OciXCrom's Admin Chat   4.2         OciXCrom          crx_adminchat.a  running  
 [ 76] Chat Manager            1.1.2-16    Mistrick          chatmanager.amx  running  
 [ 77] Chat Manager: Addon     0.0.4-70    Mistrick          chatmanager_add  running  
 [ 78] [WF] CS:GO Knife Model  1.0.0       Nordic Warrior    WF_DefaultKnife  running  
 [ 79] [WF] NightVIP           0.0.3       Nordic Warrior    WF_NightVIP.amx  running  
 [ 80] [WF] Sponsor respawn    1.0.1       Nordic Warrior    WF_Sponsor_resp  running  
 [ 81] [WF] Steam Bonus        1.0.0       Nordic Warrior    WF_Steam_bonus.  running  
 [ 82] [WF] Vampire            0.0.1a      Nordic Warrior    WF_Vampire.amxx  running  
 [ 83] [WF] VIP System         0.0.5       Nordic Warrior    WF_VIP.amxx      running  
 [ 84] [WF] Voice Splitter     1.0.0       Nordic Warrior    WF_Voice_splitt  running  
 [ 85] Map Manager: Core       3.1.5       Mistrick          map_manager_cor  running  
 [ 86] Map Manager: Scheduler  0.1.10      Mistrick          map_manager_sch  running  
 [ 87] Map Manager: Rtv        0.1.1       Mistrick          map_manager_rtv  running  
 [ 88] Map Manager: Nominatio  0.2.1       Mistrick          map_manager_nom  running  
 [ 89] Map Manager: BlockList  0.0.4       Mistrick          map_manager_blo  running  
 [ 90] Map Manager: Effects    0.1.1       Mistrick          map_manager_eff  running  
 [ 91] Map Manager: Informer   0.0.5       Mistrick          map_manager_inf  running  
91 plugins, 91 running
```

Mod: `Public`

Map: `css_inferno`

**Comment by jeefo** [comment]
судя по стёку, ошибка во время редактирования путей вылетела?

**Comment by Nord1cWarr1or** [comment]
Редактирование точно было не активно. Возможно, у меня был включен показ путей, но редактор - точно нет. На сервере находились только я и 6 ботов.

**Comment by Nord1cWarr1or** [comment]
Судя по логу, краш случился после того, как я зашёл на сервер и потом присоединился к наблюдателям:
```
L 06/15/2022 - 15:04:01: World triggered "Round_Start"
L 06/15/2022 - 15:04:07: "Nørd1c ※ Ⱳarriør<260><STEAM_0:0:101004164><>" joined team "SPECTATOR"
Segmentation fault (core dumped)
```
P.s. забыл указать ОС, Debian 9.

**Comment by jeefo** [comment]
На 10 дебиане не особо падает, но воспроизвети полную копию сервера я врядли смогу...

**Comment by Nord1cWarr1or** [comment]
@jeefo, ну на самом деле это довольно спонтанный краш, сборка не новая, и всё было нормально. Буду наблюдать дальше за падениями, если на текущий момент не понятно, в чем причина
